# Generated by Django 4.2.6 on 2023-11-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_code', models.CharField(max_length=50, unique=True)),
                ('campaign_name', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('questions', models.ManyToManyField(to='polls.question')),
            ],
        ),
    ]
