# Generated by Django 4.2.6 on 2023-11-09 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='parent_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.choice'),
        ),
    ]
