# Generated by Django 4.2.6 on 2023-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='parent_answer',
        ),
        migrations.AddField(
            model_name='condition',
            name='parent_answer',
            field=models.ManyToManyField(to='polls.choice'),
        ),
    ]
